#' Extract Transfer Values
#' n
#' \code{getValues} is a accessor function which returns the number of recovered
#' glass fragments generated by \code{\link{transfer}}.
#' 
#' 
#' @param tferObj An object of class \code{tfer}
#' @return \code{values} returns a numeric vector of random variates.
#' @export
#' @author TingYu Huang and James Curran
#' @seealso \code{\link{transfer}}
#' @examples
#' 
#' library(tfer)
#' y = transfer()
#' getValues(y)
#' 
getValues = function(tferObj)
  tferObj$results
